[GOOGLE_OAUTH_CLIENT]
client_id = "YOUR_ID"
client_secret = "YOUR_SECRET"
token_uri = "https://oauth2.googleapis.com/token"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
project_id = "YOUR_PROJECT"
